### ISSUE TITLE
Python completions not working

### ISSUE THREAD

**Issue by Decent1** [maralla/completor.vim#76]
I only get normal identifier completions + UltiSnips completions and the completions show up with slight delay. Some facts:

- Vim (8.0.311) is compiled with python3
- Jedi is installed globally with `sudo pip3 install jedi`
- Jedi is importable in `python3` shell
- In `python3` shell `print sys.executable` gives `/usr/bin/python3`
- I have `let g:completor_python_binary = "/usr/bin/python3"` in my .vimrc
- :CompletorDisable makes the (identifier+UltiSnips) completions instant
- :CompletorEnable makes the (identifier+UltiSnips) completions have slight delay
- completor.vim version is e9897d6, latest as of writing
- I have no other completers installed in Vim

What am I missing and how could I debug this more?

**Comment by maralla** [comment]
Here is way to debug python completion:

Run:
```bash
python3 /path/to/completor.vim/pythonx/completers/python/python_jedi.py -v
```
then copy the following as the input to *python_jedi.py*:
```
{"filename": "/home/vagrant/test.py", "line": 1, "col": 3, "content": "import os\nos."}
```
then press `enter` to see if there has any results.

If the results is `[]` then open the following file to see the logs:
```
/path/to/completor.vim/pythonx/completers/completor.log
```

**Comment by Decent1** [comment]
The result is a really long list of dicts. Should it be working then?

And is it normal that I get a lot of [ID] results with Completor/Jedi? I have used YCM before and it seemed to limit the results a lot more, giving more accurate suggestions and being more aware of class attributes. Using `self.` with YCM gives the class attributes/functions and parent class attributes/functions but completor doesn't. AFAIK YCM also uses Jedi, so the results should be same with YCM and completor.

Also, if I try `"something".up`, completor only suggests my Django UpdateView snippet from UltiSnip. YCM suggests: `upper function: __builtin__.str.upper` and `isupper function: __builtin__.str.isupper`.

**Comment by maralla** [comment]
Completor also suggests what YCM suggests:

![com](https://cloud.githubusercontent.com/assets/2238118/22682579/549cefbe-ed4e-11e6-9d0d-efc9f513956b.gif)

Maybe you have completor.vim and YCM both installed. They can not work together.

**Comment by Decent1** [comment]
Ok found the problem. I had `autocmd Filetype python set ft=python.django`. Commenting that one out made completor.vim work.

Still, my results look a bit different to yours:

![completor](https://cloud.githubusercontent.com/assets/8499516/22683168/50b0440c-ed1f-11e6-99fb-d884293ac916.png)

Why could this be? I tried removing all other plugins and cleared my .vimrc but no luck.

**Comment by ninjawithaneedle** [comment]
Unrelated. @maralla how do you have the documetation pop-up while completing? Do you use a combination of plugins? Would love to see your python dev setup. Thanks :)

**Comment by JokerQyou** [comment]
Just faced this problem and figured out with @maralla 's debugging tutorial. I was trying to install completor plugin as a system default for all users on a Linux box (installed to a subdirectory in `/etc/vim` ), and completor would like to write to a log file in the plugin directory, which is obviously impossible because normal users have no permission to write to `/etc/vim`.

`vim-plug` seems to provide an option named `dir` for plugins, I wonder if completor could use that directory to store log files instead?

**Comment by abidibo** [comment]
About @Decent1 problem,
I find convenient to set `autocmd Filetype python set ft=python.django` in my local vimrc for django projects, also because ultisnips will load the django snippets. Many other plugins (I think) work by matching with regexp, or perhaps dot separated words the filetype, in other words, I would expect to have python semantic completion available with a filetype which is `python.django`.

I've currenlty forced this behavior editing the `pythonx/completor/__init__.py` file, and adding a map item
`
    _type_map = {
        b'c': b'cpp',
        b'python.django': b'python',
        b'javascript.jsx': b'javascript'
    }
`
at line72.

@maralla is there a better way to support this behavior?

Thanks for this great plugin!

**Comment by maralla** [comment]
You can add this config:
```vim
let g:completor_filetype_map = {'python.django': 'python'}
```
